// packages/react/src/private/context/app.ts
import type ContextData from "@primate/i18n/ContextData";
import type Dictionary from "@rcompat/type/Dictionary";
import { createContext } from "react";

type Context = {
  i18n: ContextData;
}

type AppContext = {
  context: Context,
  setContext: React.Dispatch<Context>,
}

export default createContext<AppContext>({
  context: {
    i18n: {
      locales: {},
      locale: "en-US",
    },
  },
  setContext: (_: Dictionary) => {},
});

// packages/solid/src/private/context/app.ts
import type ContextData from "@primate/i18n/ContextData";
import { createContext, type Accessor, type Setter } from "solid-js";

type Context = {
  i18n: ContextData;
};

type AppContext = {
  context: Accessor<Context>;
  setContext: Setter<Context>;
};

export default createContext<AppContext>();
